spectaql:
  targetDir: ./build
  themeDir: ./spectaql
  # additionalImages:
  #   - ./frontend/web/svg/logo_black.svg
  displayAllServers: true
  oneFile: true

  # Optional path to your logo image which will be used as your logo in output
  logoFile: "/home/edijs/Downloads/spectaql-base/build/images/randomLogo2.jpg"

  # Optional URL to use as your logo. This should not be used with logoFile
  # If used with logoFile, this will take pecedende over the logoFile
  logoUrl: "https://cdn.prod.website-files.com/650b587646f6e012b0a00223/68c414d3b55a2e961f70cb2a_What%20is%20logo%20lockup%202.webp"

  # Control the height of your logo here
  # Default: None; No "height" property will be set on the logo
  logoHeightPx: 50

  # Optional boolean that sorts operations/types/directives alphabetically
  # Default: true
  sortAlphabetically: false

  # Optional path to your mermaid file, if you need it
  # Defaut: none
  # mermaidPath: "https://cdn.jsdelivr.net/npm/mermaid@11.12.3/dist/mermaid.min.js"

  # Optional variables to customize default themes
  # Light theme
  themeVariables:
    lightTheme:
      --spectaql-background: "red"
      --spectaql-text-color: "purple"
      --spectaql-code-copy-bg: "blue"

    # Dark theme
    darkTheme:
      --spectaql-background: "black"
      --spectaql-text-color: "#921028"
      --spectaql-code-copy-bg: "red"
      --admonition-warning-bg: "#456302"
      --text-highlight-color: "purple"
      --hljs-background: "green"

introspection:
  schemaFile: ./schema.gql
  dynamicExamplesProcessingModule: ./dynamicExamplesProcessingModule.js
  queryNameStrategy: capitalizeFirst

  # Default fieldExpansionDepth for all queries/mutations.
  # The custom depth logic is handled by customFieldExpansionDepth setting and the theme's data/index.js.
  fieldExpansionDepth: 3

  # Sets custom fieldExpansionDepth to seperate queries or mutations
  customFieldExpansionDepth:
    Query.categories: 1
    Query.items: 5
    Mutation.returnOrderCreate: 2

spectaqlDirective:
  enable: true

extensions:
  graphqlScalarExamples: true
  
servers:
    - url: https://yoursite.com/graphql
      description: Production Server
      # Indicates to use this server's URL as the typical GraphQL request base in the documentation
      # If no server entries have this indicator, the first server's URL will be used.
      # If no server entries are defined at all, the Introspection URL will be used.
      production: true
      # A place to list any Headers for your GraphQL API calls
      headers:
        - name: Authorization
          example: Bearer <YOUR_TOKEN_HERE>
          comment: Your API token from the dashboard. Must be included in all API calls.
    - url: https://yoursite.com/graphql
      description: Production Server
      # Indicates to use this server's URL as the typical GraphQL request base in the documentation
      # If no server entries have this indicator, the first server's URL will be used.
      # If no server entries are defined at all, the Introspection URL will be used.
      production: true
      # A place to list any Headers for your GraphQL API calls
      headers:
        - name: Authorization
          example: Bearer <YOUR_TOKEN_HERE>
          comment: Your API token from the dashboard. Must be included in all API calls.
#   - url: https://www.3rpms.de/graphql
#     description: Production server
#     production: true

#   - url: https://demo.3rpms.de/graphql
#     description: Sandbox server

info:
  title: 3RPMS General API Integration Knowledge Base
  description: |
    Welcome to the 3RPMS GraphQL API documentation. This API allows you to interact with the 3RPMS Property Management System.
  
    3RPMS GraphQL API is based on GraphQL. Visit https://graphql.org/ to learn more about the protocol.

  x-url: https://www.3rpms.de/graphql

  x-introItems:
    - title: Overview
      file: spectaql/documentation/overview.md

    - title: Changelog
      file: spectaql/documentation/changelog.md

    - title: GraphQL API
      items:
        - title: Why GraphQL?
          file: spectaql/documentation/graphql-api/why_graphql.md

        - title: Rate Limiting
          file: spectaql/documentation/graphql-api/rate_limiting.md

        - title: Filters
          file: spectaql/documentation/graphql-api/filters.md

        - title: Pagination
          file: spectaql/documentation/graphql-api/pagination.md

        - title: Errors
          file: spectaql/documentation/graphql-api/errors.md

        - title: Extra features
          file: spectaql/documentation/graphql-api/extra_features.md

  x-outroItems: #The documentation doesn't contain this
    - title: Webhooks
      items:
        - title: Overview
          file: spectaql/documentation/webhooks/webhooks_overview.md

        - title: Troubleshooting
          file: spectaql/documentation/webhooks/webhooks_troubleshooting.md

    - title: Guides
      items:
        - title: Using Room Access Keys
          file: spectaql/documentation/guides/room_access_keys.md

        - title: External Sales API
          file: spectaql/documentation/guides/external_sales_api.md

        - title: Rates & Restrictions API
          file: spectaql/documentation/guides/rates_and_restrictions_api.md
